[project]
name = "luxtest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "av>=14.4.0",
    "imageio[pyav]>=2.37.0",
    "moviepy>=2.2.1",
    "openimageio>=3.0.6.1",
    "tqdm>=4.67.1",
    "pefile; sys_platform == 'win32'",
    "pyelftools; sys_platform == 'linux'",
]

[dependency-groups]
usd = ["usd-core>=25.5.1"]


[tool.black]
exclude = '''
^/(
  (
    # root directories to exclude
    \.DS_Store
    | \.conan
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.vs
    | \.vscode
    | _venv
  )/
  # any rooted files to ignore would go here
)
# unrooted paths here
| __pycache__/
'''
# In different versions of black, there were 3 different ways to turn on
# the same thing - splitting up of long string literals
experimental-string-processing = true
preview = true
enable-unstable-feature = ['string_processing']

line-length = 120

[tool.isort]
profile = 'black'
lines_between_types = 1
combine_as_imports = true
line_length = 120

[tool.ruff]
line-length = 120
ignore = [
    "E402", # Module level import not at top of file
]
